download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/linode-cloud-0.41.1.tar.gz
format_version: 1.0.0
name: cloud
namespace: linode
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.41.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/linode/cloud/versions/0.41.1/
